### ISSUE TITLE
[2.0.1] segfault in test suite on 32-bit

### ISSUE THREAD

**Issue by remicollet** [runkit7/runkit7#185]
OK with PHP 7.3

Segfault with 7.2 and 7.1, only on 32-bit

TEST 94/170 [tests/runkit_import_class_extend.phpt]
========DIFF========
002+ 
003+ Termsig=11
002- n
003- n
004- done
========DONE========
FAIL runkit_import() Importing and overriding classes extending another loaded class [tests/runkit_import_class_extend.phpt]

**Comment by remicollet** [comment]
```
(gdb) bt
#0  zend_mm_alloc_small (bin_num=2, size=<optimized out>, heap=0xf7000040) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/Zend/zend_alloc.c:1275
#1  zend_mm_alloc_heap (size=<optimized out>, heap=0xf7000040) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/Zend/zend_alloc.c:1346
#2  _emalloc (size=<optimized out>) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/Zend/zend_alloc.c:2435
#3  0x5674ce0b in zend_string_alloc (persistent=0, len=3) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/Zend/zend_string.h:170
#4  zend_string_init (persistent=0, len=3, str=<optimized out>) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/Zend/zend_string.h:170
#5  lex_scan (zendlval=0xffff929c) at Zend/zend_language_scanner.l:1892
#6  0x5676197d in zendlex (elem=0xffff9320) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/Zend/zend_compile.c:1728
#7  0x56745b1d in zendparse () at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/Zend/zend_language_parser.c:4227
#8  0x567484ce in zend_compile (type=type@entry=2) at Zend/zend_language_scanner.l:585
#9  0x5674991a in compile_file (file_handle=0xffff9a20, type=2) at Zend/zend_language_scanner.l:635
#10 0x56749abd in compile_filename (type=2, filename=0xf701b190) at Zend/zend_language_scanner.l:662
#11 0xf724c5bf in zif_runkit_import (execute_data=0xf701b160, return_value=0xffff9c4c) at /builddir/build/BUILD/php-pecl-runkit7-2.0.1/NTS/runkit_import.c:561
#12 0x568266e7 in ZEND_DO_ICALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/Zend/zend_vm_execute.h:573
#13 execute_ex (ex=0x673d800) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/Zend/zend_vm_execute.h:59747
#14 0x5682e888 in zend_execute (op_array=<optimized out>, return_value=<optimized out>) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/Zend/zend_vm_execute.h:63776
#15 0x56784b9d in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/Zend/zend.c:1498
#16 0x5671fcdc in php_execute_script (primary_file=<optimized out>) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/main/main.c:2594
#17 0x56831005 in do_cli (argc=60, argv=0x569ce680) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/sapi/cli/php_cli.c:1011
#18 0x565dca89 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/php-7.2.17-1.fc29.remi.i386/sapi/cli/php_cli.c:1403

```

**Comment by TysonAndre** [comment]
Related to #150  - this also crashes in Windows in 7.3
